// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package iotendancebe

type NewUser struct {
	Username  string `json:"username"`
	UserFname string `json:"user_fname"`
	UserLname string `json:"user_lname"`
	Password  string `json:"password"`
}
